(lang dune 2.9)
(name quartic_MD)

(generate_opam_files true)

(package
  (name quartic_MD)
  (synopsis "Modular decomposition of undirected graphs")
  (depends
    (js_of_ocaml (>= 4.0))
    (base (>= 4.13))
    (yojson (>= 1.7))))